<?php

namespace AppBundle\Repository;

/**
 * MeasurePlacesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeasurePlaceRepository extends \Doctrine\ORM\EntityRepository
{
}
